# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180810_0024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribe',
            new_name='subscriber',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
