# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('-title',)},
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
