# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_auto_20180809_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='slider',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
